" Name:         Rosé Pine Moon
" Description:  Soho vibes for Vim
" Author:       Klaus-Peter Schreiner <kpschreiner13@gmail.com>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: 16.11.2021 13:32:21

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'rose_pine_moon'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link EndOfBuffer NonText
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#383652', '#eb7092', '#3d8fb0', '#f6c278',
        \ '#9ccfd9', '#c4a6e9', '#eb9996', '#e0def6', '#827d9c', '#eb7092',
        \ '#3d8fb0', '#f6c278', '#9ccfd9', '#c4a6e9', '#eb9996', '#e0def6']
  if get(g:, 'rose_pine_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#e0def6 guibg=#242136 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#e0def6 guibg=#242136 guisp=NONE gui=NONE cterm=NONE
  endif
  if get(g:, 'rose_pine_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#e0def6 guibg=#242136 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#e0def6 guibg=#242136 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#403d54 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#242136 guibg=#827d9c guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#302e45 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#29293d guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#eb9996 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#eb7092 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#eb7092 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded guifg=#e0def6 guibg=#29262e guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#302e45 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#59546e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#e0def6 guibg=#383652 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#e0def6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#c4a6e9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#827d9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#827d9c guibg=#29262e guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#383652 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#e0def6 guibg=#383652 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#59546e guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#f6c278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#c4a6e9 guibg=#403d54 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#e0def6 guibg=#242136 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#eb7092 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#3d8fb0 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#c4a6e9 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#9ccfd9 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#827d9c guibg=#383652 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#59546e guibg=#29293d guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#59546e guibg=#242136 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#242136 guibg=#403d54 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#827d9c guibg=#383652 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#eb9996 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#383652 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#302e45 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#302e45 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#f6c278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#e0def6 guibg=#29262e guisp=NONE gui=reverse cterm=reverse
  hi Comment guifg=#827d9c guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#f6c278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#eb7092 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#eb9996 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#242136 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#827d9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#c4a6e9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#eb9996 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#c4a6e9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#3d8fb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#eb9996 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#c4a6e9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#9ccfd9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#9ccfd9 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#827d9c guibg=#242136 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#e0def6 guibg=#403d54 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=189 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=189 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=189 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=189 ctermbg=235 cterm=NONE
  endif
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=189 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=189 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=189 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=189 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=238 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=235 ctermbg=103 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=189 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=152 ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=174 ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=204 ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=189 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=152 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=204 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=189 ctermbg=235 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=236 cterm=reverse
  hi LineNr ctermfg=60 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=189 ctermbg=237 cterm=NONE
  hi ModeMsg ctermfg=189 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=183 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=103 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=103 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=189 ctermbg=237 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=60 cterm=NONE
  hi Question ctermfg=222 ctermbg=NONE cterm=NONE
  hi Search ctermfg=183 ctermbg=238 cterm=NONE
  hi SignColumn ctermfg=189 ctermbg=235 cterm=NONE
  hi SpecialKey ctermfg=152 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=103 ctermbg=237 cterm=NONE
  hi StatusLineNC ctermfg=60 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=60 ctermbg=235 cterm=NONE
  hi TabLineFill ctermfg=235 ctermbg=238 cterm=NONE
  hi TabLineSel ctermfg=103 ctermbg=237 cterm=NONE
  hi Title ctermfg=174 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=237 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=236 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=236 cterm=NONE
  hi WarningMsg ctermfg=222 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=189 ctermbg=235 cterm=reverse
  hi Comment ctermfg=103 ctermbg=NONE cterm=italic
  hi Constant ctermfg=222 ctermbg=NONE cterm=NONE
  hi Error ctermfg=204 ctermbg=NONE cterm=NONE
  hi Function ctermfg=152 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=174 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=235 ctermbg=NONE cterm=NONE
  hi Label ctermfg=152 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=103 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=183 ctermbg=NONE cterm=NONE
  hi Special ctermfg=174 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=183 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=31 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=174 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=183 ctermbg=NONE cterm=NONE
  hi Type ctermfg=152 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=152 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=103 ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=189 ctermbg=238 cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
    hi Terminal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  endif
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
    hi Terminal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightCyan cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightMagenta cterm=NONE
  hi CursorLineNr ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Directory ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=DarkMagenta ctermbg=DarkRed cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightBlue cterm=reverse
  hi LineNr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi ModeMsg ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=DarkBlue ctermbg=DarkRed cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi PmenuSel ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Search ctermfg=LightYellow ctermbg=LightCyan cterm=NONE
  hi SignColumn ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=DarkBlue ctermbg=DarkGreen cterm=NONE
  hi StatusLineNC ctermfg=DarkYellow ctermbg=LightMagenta cterm=NONE
  hi TabLine ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightCyan cterm=NONE
  hi TabLineSel ctermfg=DarkBlue ctermbg=DarkGreen cterm=NONE
  hi Title ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=DarkMagenta ctermbg=DarkRed cterm=reverse
  hi Comment ctermfg=DarkBlue ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi Label ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Tag ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkMagenta ctermbg=LightCyan cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: base          rgb( 36,  33,  54)        ~         Black
" Color: surface       rgb( 41,  38,  46)        ~         DarkRed
" Color: overlay       rgb( 56,  54,  82)        ~         DarkGreen
" Color: inactive      rgb( 89,  84, 110)        ~         DarkYellow
" Color: subtle        rgb(130, 125, 156)        ~         DarkBlue
" Color: text          rgb(224, 222, 246)        ~         DarkMagenta
" Color: love          rgb(235, 112, 146)        ~         DarkCyan
" Color: gold          rgb(246, 194, 120)        ~         LightGrey
" Color: rose          rgb(235, 153, 150)        ~         DarkGrey
" Color: pine          rgb( 61, 143, 176)        ~         LightRed
" Color: foam          rgb(156, 207, 217)        ~         LightGreen
" Color: iris          rgb(196, 166, 233)        ~         LightYellow
" Color: highlight     rgb( 48,  46,  69)        ~         LightBlue
" Color: hlInactive    rgb( 41,  41,  61)        ~         LightMagenta
" Color: hlOverlay     rgb( 64,  61,  84)        ~         LightCyan
" Color: white         aqua                      ~         White
" Color: black         lime                      ~         Black
" Term colors: overlay love pine gold foam iris rose text
" Term colors: subtle love pine gold foam iris rose text
" vim: et ts=2 sw=2
