" Name:         Rosé Pine Dawn
" Description:  Soho vibes for Vim
" Author:       Klaus-Peter Schreiner <kpschreiner13@gmail.com>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: 17.11.2021 14:50:25

" Generated by Colortemplate v2.0.0

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'rose_pine_dawn'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link EndOfBuffer NonText
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#f2e8de', '#b5637a', '#296982', '#eb9e33',
        \ '#57949e', '#8f7aa8', '#d6827d', '#575278', '#6e6b87', '#b5637a',
        \ '#296982', '#eb9e33', '#57949e', '#8f7aa8', '#d6827d', '#575278']
  if get(g:, 'rose_pine_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#575278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#575278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#575278 guibg=#faf6ed guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#575278 guibg=#faf6ed guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#e3dede guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#faf6ed guibg=#6e6b87 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#ede8e6 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f2ede8 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#575278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#d6827d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#b5637a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#575278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#b5637a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded guifg=#575278 guibg=#fffaf2 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#ede8e6 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#9994a6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#575278 guibg=#f2e8de guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#575278 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#8f7aa8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#6e6b87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#6e6b87 guibg=#fffaf2 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#f2e8de guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#575278 guibg=#f2e8de guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#9994a6 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#eb9e33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#8f7aa8 guibg=#e3dede guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#575278 guibg=#faf6ed guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#b5637a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#296982 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#8f7aa8 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#57949e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#6e6b87 guibg=#f2e8de guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#9994a6 guibg=#f2ede8 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#9994a6 guibg=#faf6ed guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#faf6ed guibg=#e3dede guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#6e6b87 guibg=#f2e8de guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#d6827d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#f2e8de guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#ede8e6 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#ede8e6 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#eb9e33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#575278 guibg=#fffaf2 guisp=NONE gui=reverse cterm=reverse
  hi Comment guifg=#6e6b87 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#eb9e33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#b5637a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#d6827d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#faf6ed guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#6e6b87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#8f7aa8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#d6827d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#8f7aa8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#296982 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#d6827d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#8f7aa8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#57949e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#57949e guibg=NONE guisp=NONE gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#6e6b87 guibg=#faf6ed guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#575278 guibg=#e3dede guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=60 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=60 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=60 ctermbg=255 cterm=NONE
    hi Terminal ctermfg=60 ctermbg=255 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=254 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=255 ctermbg=60 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=254 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=60 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=66 ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=174 ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=132 ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=60 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=66 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=132 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=60 ctermbg=231 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=254 cterm=reverse
  hi LineNr ctermfg=103 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=60 ctermbg=255 cterm=NONE
  hi ModeMsg ctermfg=60 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=103 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=60 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=60 ctermbg=231 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=60 ctermbg=255 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=103 cterm=NONE
  hi Question ctermfg=172 ctermbg=NONE cterm=NONE
  hi Search ctermfg=103 ctermbg=254 cterm=NONE
  hi SignColumn ctermfg=60 ctermbg=255 cterm=NONE
  hi SpecialKey ctermfg=66 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=60 ctermbg=255 cterm=NONE
  hi StatusLineNC ctermfg=103 ctermbg=255 cterm=NONE
  hi TabLine ctermfg=103 ctermbg=255 cterm=NONE
  hi TabLineFill ctermfg=255 ctermbg=254 cterm=NONE
  hi TabLineSel ctermfg=60 ctermbg=255 cterm=NONE
  hi Title ctermfg=174 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=255 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=254 cterm=NONE
  hi WarningMsg ctermfg=172 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=60 ctermbg=231 cterm=reverse
  hi Comment ctermfg=60 ctermbg=NONE cterm=italic
  hi Constant ctermfg=172 ctermbg=NONE cterm=NONE
  hi Error ctermfg=132 ctermbg=NONE cterm=NONE
  hi Function ctermfg=66 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=174 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
  hi Label ctermfg=66 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=60 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=103 ctermbg=NONE cterm=NONE
  hi Special ctermfg=174 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=103 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=24 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=174 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=103 ctermbg=NONE cterm=NONE
  hi Type ctermfg=66 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=66 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=60 ctermbg=255 cterm=NONE
  hi ToolbarButton ctermfg=60 ctermbg=254 cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'rose_pine_transp_bg', 0)
    hi Normal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
    if !has('patch-8.0.0616')
      set background=light
    endif
    hi Terminal ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightCyan cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightMagenta cterm=NONE
  hi CursorLineNr ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Directory ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=DarkMagenta ctermbg=DarkRed cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightBlue cterm=reverse
  hi LineNr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi ModeMsg ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=DarkBlue ctermbg=DarkRed cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi PmenuSel ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Search ctermfg=LightYellow ctermbg=LightCyan cterm=NONE
  hi SignColumn ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=DarkBlue ctermbg=DarkGreen cterm=NONE
  hi StatusLineNC ctermfg=DarkYellow ctermbg=LightMagenta cterm=NONE
  hi TabLine ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightCyan cterm=NONE
  hi TabLineSel ctermfg=DarkBlue ctermbg=DarkGreen cterm=NONE
  hi Title ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=DarkMagenta ctermbg=DarkRed cterm=reverse
  hi Comment ctermfg=DarkBlue ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi Label ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Tag ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkMagenta ctermbg=LightCyan cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: base          rgb(250, 246, 237)        ~         Black
" Color: surface       rgb(255, 250, 242)        ~         DarkRed
" Color: overlay       rgb(242, 232, 222)        ~         DarkGreen
" Color: inactive      rgb(153, 148, 166)        ~         DarkYellow
" Color: subtle        rgb(110, 107, 135)        ~         DarkBlue
" Color: text          rgb( 87,  82, 120)        ~         DarkMagenta
" Color: love          rgb(181,  99, 122)        ~         DarkCyan
" Color: gold          rgb(235, 158,  51)        ~         LightGrey
" Color: rose          rgb(214, 130, 125)        ~         DarkGrey
" Color: pine          rgb( 41, 105, 130)        ~         LightRed
" Color: foam          rgb( 87, 148, 158)        ~         LightGreen
" Color: iris          rgb(143, 122, 168)        ~         LightYellow
" Color: highlight     rgb(237, 232, 230)        ~         LightBlue
" Color: hlInactive    rgb(242, 237, 232)        ~         LightMagenta
" Color: hlOverlay     rgb(227, 222, 222)        ~         LightCyan
" Color: white         black                     ~         White
" Color: black         lime                      ~         Black
" Term colors: overlay love pine gold foam iris rose text
" Term colors: subtle love pine gold foam iris rose text
" vim: et ts=2 sw=2
